version : '1'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solutions
    ports:
      - '5432:5432'
    volumes:
      - queens_db:/var/lib/postgresql/data
    networks:
      - challenge_net
    container_name: challenge_db
  # queens:
  #   image: queens
  #   depends_on:
  #     - database
  #   stdin_open: true
  #   tty: true
volumes:
  queens_db:
    driver: local
networks:
  challenge_net:
    driver: bridge
    name: challenge_net

